version: '3.8'

services:

    # nginx
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        build:
            context: ./web
            args:
                - NGINX_VERSION=${NGINX_VERSION}
        ports:
            - "${WEB_HTTP_PORT}:80"
            - "${WEB_SSL_PORT}:443"
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx.conf
            - ./web/conf.d/:/etc/nginx/conf.d/
            - ../src:/var/www/vhosts
        depends_on:
            - app

    # app
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build:
            context: ./app
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        command: >
            sh -c "if [ ! -f /var/www/vhosts/manage.py ]; then
                    django-admin startproject mysite .;
                    fi &&
                    gunicorn mysite.wsgi:application --bind 0.0.0.0:80"
        volumes:
            - ../src:/var/www/vhosts
        environment:
            - DEBUG=True
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=${DB_PORT}
            - DJANGO_DB_NAME=${DB_DATABASE}
            - DJANGO_DB_USER=${DB_USER}
            - DJANGO_DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db

    # db
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        build:
            context: ./db
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - db-store:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
    db-store:
        name: ${COMPOSE_PROJECT_NAME}_db_store