version: '3.8'

services:

    # nginx
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        build: ./nginx
        ports:
            - "${WEB_HTTP_PORT}:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ../src:/var/www/vhosts
        depends_on:
            - app

    # app
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build:
            context: ./app
            args:
                - DJANGO_VERSION=${DJANGO_VERSION}
        command: gunicorn wsgi:application --bind 0.0.0.0:80
        volumes:
            - ../src:/var/www/vhosts
        environment:
            - DEBUG=True
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=3306
            - DJANGO_DB_NAME=${DB_DATABASE}
            - DJANGO_DB_USER=${DB_USER}
            - DJANGO_DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db

    # db
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        build:
            context: ./mariadb
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db-store:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    db-store:
        name: ${COMPOSE_PROJECT_NAME}_db_store